
development:
  adapter: postgresql
  encoding: unicode
  database: bambu_solar_admin_development
  host: localhost
  pool: 5
  username: postgres
  password: 


test:
  adapter: postgresql
  encoding: unicode
  database: bambu_solar_admin_test
  host: localhost
  pool: 5
  username: postgres
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: bambu_solar_admin_production
  host: localhost
  pool: 5
  username: postgres
  password: 
