# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ee2279aebc10aebb93caea6962e47da33200ccb666f8dcdc4713d767013cb65246b4ccd2b70c779ec63ed5674688089cd7c3cd1a72e7ed0f5a028d5960588d0

test:
  secret_key_base: ef70497f67f2713b56c57dbc913b526e251f7ca8cb773b30b4bfaef0d138a0d387510caf9a2ac97937f68a8fe4977ff0fb3b8b7dc5b83e60d2bcbd1e35e7b54c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8f6fc637a065bf7b79d57eea84fe6c12bc219e88def8da9f643a08d6f3f4b3ddd7ee2e20e08cb0e58610a5a6010f0a1de6bc9173396b6255bf7051b782817b2e
